services:
  simple-service-with-browser:
    image: devopsdockeruh/simple-web-service
    container_name: simple-service-with-browser-compose
    command: server
    ports:
        - "127.0.0.1:8080:8080"