services:
  frontend:
    image: example-frontend
    ports:
      - "127.0.0.1:5000:5000"
  backend:
    image: example-backend
    restart: unless-stopped
    ports:
     - "127.0.0.1:8080:8080"
    environment:
     REDIS_HOST: "redis-cache"
  redis-cache:
    image: redis